export const infinitives = {
    'hablar': 'to speak',
    'cantar': 'to sing',
    'bailar': 'to dance',
    'trabajar': 'to work',
    'estudiar': 'to study',
    'caminar': 'to walk',
    'mirar': 'to look (at)',
    'escuchar': 'to listen (to)',
    'llegar': 'to arrive',
    'comprar': 'to buy',
    'llamar': 'to call',
    'viajar': 'to travel',
    'ayudar': 'to help',
    'nadar': 'to swim',
    'pintar': 'to paint',
    'cocinar': 'to cook',
    'limpiar': 'to clean',
    'visitar': 'to visit',
    'esperar': 'to wait (for), to hope',
    'preguntar': 'to ask (a question)',
};